# Generated by Django 5.0.2 on 2026-09-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shootdayscene',
            options={
                'ordering': ['shoot_day', 'shot_order'],
                'unique_together': (('shoot_day', 'scene'),),
                'verbose_name': 'Shoot Day Scene',
                'verbose_name_plural': 'Shoot Day Scenes',
            },
        ),
    ]