# Generated by Django 5.0.2 on 2026-09-24 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_shootdayscene_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shootdayscene',
            options={'managed': False, 'ordering': ['shoot_day', 'shot_order'], 'verbose_name': 'Shoot Day Scene', 'verbose_name_plural': 'Shoot Day Scenes'},
        ),
    ]
