# Generated by Django 5.2.5 on 2026-09-13 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBudgetAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('anomaly_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ai_budget_anomalies', to='production.filmproject')),
            ],
            options={
                'db_table': 'ai_budget_anomalies',
            },
        ),
        migrations.CreateModel(
            name='AICastRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_description', models.CharField(blank=True, max_length=200, null=True)),
                ('match_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ai_cast_recommendations', to='production.filmproject')),
                ('recommended_cast', models.ForeignKey(blank=True, db_column='cast_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='production.castmember')),
            ],
            options={
                'db_table': 'ai_cast_recommendations',
            },
        ),
        migrations.CreateModel(
            name='AIFestivalWin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('festival_name', models.CharField(blank=True, max_length=100, null=True)),
                ('win_probability', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('tier', models.CharField(blank=True, max_length=20, null=True)),
                ('factors', models.JSONField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ai_festival_wins', to='production.filmproject')),
            ],
            options={
                'db_table': 'ai_festival_wins',
            },
        ),
        migrations.CreateModel(
            name='AILocationRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommended_location', models.CharField(blank=True, max_length=200, null=True)),
                ('match_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ai_location_recommendations', to='production.filmproject')),
                ('scene', models.ForeignKey(blank=True, db_column='scene_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ai_location_recommendations', to='production.scene')),
            ],
            options={
                'db_table': 'ai_location_recommendations',
            },
        ),
        migrations.CreateModel(
            name='AIRiskForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forecast_date', models.DateField(blank=True, null=True)),
                ('risk_type', models.CharField(blank=True, max_length=50, null=True)),
                ('predicted_probability', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('predicted_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('rationale', models.TextField(blank=True, null=True)),
                ('preventive_action', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ai_risk_forecasts', to='production.filmproject')),
            ],
            options={
                'db_table': 'ai_risk_forecasts',
            },
        ),
        migrations.CreateModel(
            name='AISceneDurationPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('actual_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('complexity_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scene', models.ForeignKey(blank=True, db_column='scene_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ai_duration_predictions', to='production.scene')),
            ],
            options={
                'db_table': 'ai_scene_duration_predictions',
            },
        ),
        migrations.CreateModel(
            name='AIScriptAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('character_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dialogue_excerpt', models.TextField(blank=True, null=True)),
                ('polarity', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('subjectivity', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('dominant_emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('emotion_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('intensity_level', models.CharField(blank=True, max_length=20, null=True)),
                ('pacing_suggestion', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ai_script_analyses', to='production.filmproject')),
                ('scene', models.ForeignKey(blank=True, db_column='scene_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ai_analyses', to='production.scene')),
            ],
            options={
                'db_table': 'ai_script_analysis',
            },
        ),
    ]
