# Generated by Django 5.0.2 on 2026-09-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CREW', 'CREW MEMBER'), ('USER', 'GENERAL USER')], default='USER', max_length=10),
        ),
    ]
