# Generated by Django 5.0.2 on 2026-09-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('CREW', 'CREW MEMBER'), ('USER', 'GENERAL USER')], default='USER', max_length=10),
        ),
    ]
